In [28]:
import pandas as pd
import numpy as np
 
V=np.array((1,3,3,2,3,3,3,2,1,2,1,1,3,1,3,3,3))
print(V)

[1 3 3 2 3 3 3 2 1 2 1 1 3 1 3 3 3]


In [21]:
# Transition Probabilities
a = np.array(((0.5, 0.5), (0.4, 0.6)))
 
# Emission Probabilities
b = np.array(((0.5, 0.4, 0.1), (0.2, 0.4, 0.4)))
#b = np.array(((0.5,0.2), (0.4,0.4),(0.1,0.4)))
# Equal Probabilities for the initial distribution
initial_distribution = np.array((0.2, 0.8))

In [22]:
def forward(V, a, b, initial_distribution):
    alpha = np.zeros((V.shape[0], a.shape[0]))
    alpha[0, :] = initial_distribution * b[:, V[0]]
 
    for t in range(1, V.shape[0]):
        for j in range(a.shape[0]):
            # Matrix Computation Steps
            #                  ((1x2) . (1x2))      *     (1)
            #                        (1)            *     (1)
            alpha[t, j] = alpha[t - 1].dot(a[:, j])* b[j, V[t]-1]
 
    return alpha
 
alpha = forward(V, a, b, initial_distribution)
print(alpha)
#alpha[t,i]=P("последовательность видимых значений длины t",s(t)=i);i-состояния

[[8.00000000e-02 3.20000000e-01]
 [1.68000000e-02 9.28000000e-02]
 [4.55200000e-03 2.56320000e-02]
 [5.01152000e-03 7.06208000e-03]
 [5.33059200e-04 2.69720320e-03]
 [1.34541088e-04 7.53940608e-04]
 [3.68846787e-05 2.07853964e-04]
 [4.06335699e-05 5.72618870e-05]
 [2.16107699e-05 1.09347834e-05]
 [6.07171932e-06 6.94650200e-06]
 [2.90723023e-06 1.44075217e-06]
 [1.01495799e-06 4.63613284e-07]
 [6.92924310e-08 3.14258786e-07]
 [8.01748650e-08 4.46402975e-08]
 [5.79435515e-09 2.67486444e-08]
 [1.35966353e-09 7.57854569e-09]
 [3.71125004e-10 2.09078367e-09]]


In [23]:
like=alpha[V.shape[0]-1,0]+alpha[V.shape[0]-1,1]
print(like)

2.4619086756233884e-09


In [62]:
checkseemsbad=np.random.randint(1, 4, 500)
#print(check)
alpha = forward(checkseemsbad, a, b, initial_distribution)
print(alpha)

[[8.00000000e-002 3.20000000e-001]
 [1.68000000e-002 9.28000000e-002]
 [4.55200000e-003 2.56320000e-002]
 [1.25288000e-003 7.06208000e-003]
 [1.72563600e-003 9.72737600e-004]
 [1.25191304e-004 5.78584224e-004]
 [1.17611737e-004 1.63898475e-004]
 [4.97461033e-005 6.28579812e-005]
 [2.00064976e-005 2.50351361e-005]
 [2.00173033e-006 1.00097322e-005]
 [2.00190322e-006 2.80268179e-006]
 [8.48809731e-007 1.07302427e-006]
 [8.53614575e-008 4.27287772e-007]
 [2.13595838e-008 1.19621357e-007]
 [5.85283346e-009 3.29810424e-008]
 [8.05941684e-009 4.54300843e-009]
 [2.33876472e-009 2.70220539e-009]
 [1.12513226e-009 5.58141119e-010]
 [3.14329031e-010 3.58980320e-010]
 [1.50378322e-010 7.45105415e-011]
 [5.24966887e-011 2.39790971e-011]
 [1.43359933e-011 1.62543211e-011]
 [6.83486253e-012 3.38411785e-012]
 [4.77107841e-013 2.17916079e-012]
 [5.55109118e-013 3.09210079e-013]
 [1.60495436e-013 1.85232243e-013]
 [1.54340615e-014 7.65548255e-014]
 [1.53355844e-014 2.14599704e-014]
 [1.62517804e-015 8.

In [48]:
check=np.random.randint(1, 4, 100)
#print(check)
alpha = forward(check, a, b, initial_distribution)
#print(alpha)

In [57]:
def forwardlog(V, a, b, initial_distribution):
    alpha = np.zeros((V.shape[0], a.shape[0]))
    alpha[0, :] = np.log(initial_distribution) + np.log(b[:, V[0]])
 
    for t in range(1, V.shape[0]):
        for j in range(a.shape[0]):
            # Matrix Computation Steps
            #                  ((1x2) . (1x2))      *     (1)
            #                        (1)            *     (1)
            alpha[t, j] = np.log(np.exp(alpha[t - 1].dot(a[:, j])+np.log( b[j, V[t]-1])))
            #alpha[t, j] = np.log(np.exp(alpha[t - 1].dot(a[:, j]))* b[j, V[t]-1])
    return alpha
beta = forwardlog(V, a, b, initial_distribution)
#print(beta)
print(np.exp(beta))

[[8.00000000e-02 3.20000000e-01]
 [1.79310196e-02 5.71077398e-02]
 [4.26069534e-03 9.61345432e-03]
 [4.07335272e-03 1.60889578e-03]
 [4.87065282e-04 5.38211221e-04]
 [1.08686270e-04 9.64773192e-05]
 [2.58141265e-05 1.62480958e-05]
 [2.46779850e-05 2.71938183e-06]
 [1.47541070e-05 4.54848701e-07]
 [4.46337359e-06 2.40567320e-07]
 [2.37846232e-06 4.51443697e-08]
 [8.89118363e-07 1.20764779e-08]
 [6.41587518e-08 6.69428126e-09]
 [6.80580559e-08 6.31074049e-10]
 [5.45094624e-09 3.15172237e-10]
 [1.16857107e-09 5.88064162e-11]
 [2.76437814e-10 9.94357113e-12]]


In [73]:
checkseemsgood=np.random.randint(1, 4, 600)
#print(check)
print(forwardlog(checkseemsgood, a, b, initial_distribution))

[[-2.52572864 -1.13943428]
 [-2.41178522 -3.5559628 ]
 [-3.54456846 -4.25576102]
 ...
 [       -inf        -inf]
 [       -inf        -inf]
 [       -inf        -inf]]


D:\anaconda\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in log
  # This is added back by InteractiveShellApp.init_path()
